### PR TITLE
DPI Support for MoonToggle

### PR DESCRIPTION
**Pull request by vadiscode**
It's all right now
100% DPI: 

125% DPI:

150% DPI:

And so on.

### CODE REVIEW

**Comment by hellzerg** [comment]
Very nice, will try it! Preparing for the next version...

**Comment by vadiscode** [comment]
> Very nice, will try it! Preparing for the next version...

@hellzerg Yeah I get it, I also have thoughts of adding something incredibly cool in terms of visual design to the new version.

**Comment by hellzerg** [comment]
@vadiscode Like what? :O

**Comment by vadiscode** [comment]
@hellzerg I think to implement something with TabControl, and in general I have plans to replace all standard Windows controls with custom ones with support for the color theme of the program.

**Comment by hellzerg** [comment]
@vadiscode This seems like a crazy effort. Are you sure you want to do this?

**Comment by vadiscode** [comment]
@hellzerg At least I'll try :)

**Pull request merged**
