### PR TITLE
Add Polish Translation

### PR DESCRIPTION
**Pull request by factuall**

### CODE REVIEW

**Comment by hellzerg** [comment]
This is the correct Polish translation, right?

**Comment by factuall** [comment]
Yeah, I'm polish native. I compiled source and checked it to make sure
contexts are right. Btw we have this weird random thing - Sometimes we
translate names (like HomeGroup Superfetch, Sticky Keys) and sometimes just
not. Later I will check some of the names once again with Polish Windows
version.

czw., 31 mar 2022 o 10:28 deadmoon ***@***.***> napisał(a):

**Comment by kamack38** [comment]
Why it has been closed?

**Comment by hellzerg** [comment]
Because Polish language has been added in v12.5.

**Pull request closed without merging**
