### PR TITLE
Redesigning the visual layout of the program

### PR DESCRIPTION
**Pull request by vadiscode**
I added a new button style, replaced all the standard Windows buttons with MoonButtons.

old button (the usual square button):
old
new button (rounded button):
new

### CODE REVIEW

**Comment by vadiscode** [comment]
I will also add a new ComboBox soon, i'm already working on it.

**Comment by hellzerg** [comment]
Ohh that's really fast haha. Just don't forget to support DPI scaling.

@vadiscode

**Comment by vadiscode** [comment]
@hellzerg, combobox is ready! I also removed the old MoonSelect and replaced it with the new MoonComboBox.

**Comment by vadiscode** [comment]
CheckBoxes, RadioButtons, and other small controllers will also be implemented soon.

**Comment by clownidze1337** [comment]
@vadiscode 
Could you change:

русский to Русский ?

Thanks

**Comment by hellzerg** [comment]
@vadiscode 

Can you fix the animated toggle because the animation rate is really slow, like 1 FPS.
I want to release the new version today.

**Comment by hellzerg** [comment]
@vadiscode The animationTimer must be stopped after the animation completes. Current implementation keeps the timer running, so because there are many toggles in form, multiple timers are constantly running and the performance is dropped.

**Comment by vadiscode** [comment]
@hellzerg Okay, I got it. I'll take a look.

**Comment by vadiscode** [comment]
Tomorrow I'll take care of all these problems, and I'll finish the other elements as well.

**Comment by hellzerg** [comment]
@vadiscode 

Hi, do you have Skype so we can work together to address the issues?

**Comment by vadiscode** [comment]
@hellzerg
I don't use Skype, but I have a discord. I am not working on the program now, because at the moment I have very little free time (I will continue to work as soon as it appears)

**Comment by hellzerg** [comment]
Ok, let's collaborate on Discord @vadiscode

**Comment by hellzerg** [comment]
@vadiscode 

I think the best solution here is to go for complete overhaul of the project using WPF forms.

**Comment by vadiscode** [comment]
@hellzerg 
I do not recommend using WPF, as it can degrade the performance of the program, and significantly increase the weight.

**Comment by hellzerg** [comment]
@vadiscode The custom tab control needs some bugfixing. Can you do it?

**Comment by vadiscode** [comment]
@hellzerg 
Yeah, I can look

**Comment by hellzerg** [comment]
@vadiscode 
It needs better scaling regarding tab headers

**Pull request closed without merging**
