### PR TITLE
Fully updated theme management (logo and banner supported)

### PR DESCRIPTION
**Pull request by vadiscode**
I have completely finished doing my implementation of the new theme management, it fully works and fulfills its intended functions. 

The new theme management also supports and saves user settings in the **config**, after restarting the program the selected color remains as it was set! (**LOGO** and loading **BANNER** supported)

Now instead of a lot of png files of colored logos and banners, just one file!

soft
loadingbanner

### CODE REVIEW

**Comment by hellzerg** [comment]
But the text color needs to be changed too, for some colors.

**Comment by vadiscode** [comment]
> But the text color needs to be changed too, for some colors.

Do you mean the color of the text on the buttons? Or where?

**Comment by hellzerg** [comment]
Yes, the color of the text. I will implement an automatic solution.

**Comment by vadiscode** [comment]
Alright!

**Comment by johnyboy1** [comment]
Damn @vadiscode this shit is hot 🔥🔥🔥🔥🔥

**Comment by vadiscode** [comment]
@hellzerg the new tweak (NVIDIA Telemetry) I added disables all types of NVIDIA telemetry.

pic

**Comment by kalimaenergy** [comment]
> 

Hello , i don't know if the right place for suggestion ( sorry i don't use github) 

For optimization for AMD GPU , you can disable "AMD Crash Defender Service", it's a service for detect when a crash happens and make a report to AMD.

**Comment by vadiscode** [comment]
> For optimization for AMD GPU , you can disable "AMD Crash Defender Service", it's a service for detect when a crash happens and make a report to AMD.

@kalimaenergy thanks, I'll try to do that, or @hellzerg

**Pull request closed without merging**
