### PR TITLE
Cleaning up unused resources and minor code-quality fixes

### PR DESCRIPTION
**Pull request by vadiscode**

### CODE REVIEW

**Comment by vadiscode** [comment]
> Why removing all the image assets?

I only deleted unused assets, which in fact only increase the weight of the program.

**Comment by hellzerg** [comment]
They are not unused, I think.

**Comment by vadiscode** [comment]
If they were used, I would not be able to compile the project.

**Comment by hellzerg** [comment]
But it will run without some images.

**Comment by vadiscode** [comment]
You can even completely search all the files for the names of these assets, they are not used anywhere, they are just loaded as resources and that's it, but they are not used anywhere in the code and in the program, their purpose is to increase the weight of the program...

**Comment by hellzerg** [comment]
Okay, I will look into it.

**Pull request closed without merging**
