### PR TITLE
Update .NET Framework to 4.8

### PR DESCRIPTION
**Pull request by marco-carvalho**

### CODE REVIEW

**Comment by hellzerg** [comment]
I don't wish to update .NET framework from 4.5.2 to 4.8.

**Comment by montlikadani** [comment]
Why? It has many optimizations since then.

**Comment by hellzerg** [comment]
But, it will require to install the extra framework on Windows 8/8.1.

**Comment by montlikadani** [comment]
Yea, what about separating optimizer project into 3 different project, so the first one built with 4.5.2 (win 7-8), the second with 4.6 (win10) and the third one with 4.8 (win11)

**Comment by marco-carvalho** [comment]
Just a quick reminder that anything below 4.6.2 reached EOL https://devblogs.microsoft.com/dotnet/net-framework-4-5-2-4-6-4-6-1-will-reach-end-of-support-on-april-26-2022/

**Comment by marco-carvalho** [comment]
> But, it will require to install the extra framework on Windows 8/8.1.

Windows 8.1 support will end on January 10, 2023 https://support.microsoft.com/en-us/windows/windows-8-1-support-will-end-on-january-10-2023-3cfd4cde-f611-496a-8057-923fba401e93

**Comment by hellzerg** [comment]
But it will not be run out of the box on Windows 8.1 machines. They will need the extra framework installation.

**Comment by montlikadani** [comment]
I mean in the current state it will work if you separate it into different project. As in the current state optimizer works on windows 7-8, am I right? So what I mean is, this project could be made for window 7-8 (so nothing you need to do), the second different project (not conflicting with this) would be only for windows 10 with net 6 etc.. etc.

Windows 7-8.1 users would download optimizer with integrated net 4.5 version (current state, no code changes)
Windows 10 users would download optimizer with integrated net 4.6 or .7 version (different project, maybe code changes required)
Windows 11 users would download optimizer with integrated net 4.8 version (different project, maybe code changes required)

^ all these can be done on different branches or idk somewhere else like in different repository

In integrated .net version I mean in Windows itself, so users doesn't need to install anything, they just need this optimizer executable file to be downloaded.

**Comment by hellzerg** [comment]
Yes, and this technique will also require to the update mechanism, according to which version you already have, based on .NET framework version, etc.

**Comment by hellzerg** [comment]
From v14.8 the app runs on .NET Framework 4.8.

**Pull request closed without merging**
